import type { Metadata } from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared";

const montserrat = Montserrat({
  subsets: ['cyrillic'],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Сладкий сундук",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link data-rh="true" rel="icon" href="/cupcake.png" />
      </head>
      <body className={montserrat.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
